### ISSUE TITLE
No such file or directory: nvdcpematch-1.0.json

### ISSUE THREAD

**Issue by J08nY** [crocs-muni/sec-certs#121]
Running
```sh
fips-certs new-run --output fips_dataset --name fips_dataset
```
after a fresh install of the tool results in:
```python
Traceback (most recent call last):
  File "sec-certs/virt/bin/fips-certs", line 33, in <module>
    sys.exit(load_entry_point('sec-certs', 'console_scripts', 'fips-certs')())
  File "sec-certs/virt/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "sec-certs/virt/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "sec-certs/virt/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "sec-certs/virt/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "sec-certs/fips_cli.py", line 217, in main
    dset.finalize_results()
  File "sec-certs/sec_certs/serialization/json.py", line 51, in inner_func
    result = func(*args, **kwargs)
  File "sec-certs/sec_certs/dataset/fips.py", line 421, in finalize_results
    self.compute_cpe_heuristics()
  File "sec-certs/sec_certs/serialization/json.py", line 51, in inner_func
    result = func(*args, **kwargs)
  File "sec-certs/sec_certs/dataset/dataset.py", line 211, in compute_cpe_heuristics
    return self._compute_cpe_matches()
  File "sec-certs/sec_certs/dataset/dataset.py", line 197, in _compute_cpe_matches
    cve_dset = self._prepare_cve_dataset(False)
  File "sec-certs/sec_certs/dataset/dataset.py", line 175, in _prepare_cve_dataset
    cve_dataset.build_lookup_dict(use_nist_cpe_matching_dict, self.nist_cve_cpe_matching_dset_path)
  File "sec-certs/sec_certs/dataset/cve.py", line 68, in build_lookup_dict
    matching_dict = self.get_nist_cpe_matching_dict(nist_matching_filepath)
  File "sec-certs/sec_certs/dataset/cve.py", line 202, in get_nist_cpe_matching_dict
    with unzipped_path.open('r') as handle:
  File "/usr/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp19xbck6o/nvdcpematch-1.0.json'
```

Re-running the same command afterwards results in a different error further down the processing pipeline.

**Comment by J08nY** [comment]
The following code in `sec_certs.dataset.cve.CVEDataset.get_nist_cpe_matching_dict`is the issue:

```python
        logger.debug('Attempting to get NIST mapping file.')
        if not input_filepath or not input_filepath.is_file():
            logger.debug('NIST mapping file not available, going to download.')
            with tempfile.TemporaryDirectory() as tmp_dir:
                filename = Path(self.cpe_match_feed_url).name
                download_path = Path(tmp_dir) / filename
                unzipped_path = Path(tmp_dir) / filename.rstrip('.zip')
                helpers.download_file(self.cpe_match_feed_url, download_path)

                with zipfile.ZipFile(download_path, 'r') as zip_handle:
                    zip_handle.extractall(tmp_dir)
                if input_filepath:
                    logger.debug(f'Copying attained NIST mapping file to {input_filepath}')
                    shutil.move(unzipped_path, input_filepath)
        else:
            unzipped_path = input_filepath

        with unzipped_path.open('r') as handle:
            match_data = json.load(handle)
```
where `input_filepath` is an argument to the function. If it is `None`, then
the NIST mapping file is downloaded into a temporary directory and extracted there,
and `unzipped_path` points to a temporary directory which ceases to exist as soon
as the with-block is exited. If it is a path to a directory, the NIST mapping file is also
downloaded into a temporary directory and extracted there, and the NIST mapping
file is also moved to the directory `input_filepath` but the `unzipped_path` still points
to the temporary directory which ceases to exist.
The opening of the `unzipped_path` then errors out.

I am unsure how this should be fixed and what the behavior should be. Moving the
actual opening of the file into the with-block is one possible solution.
