### ISSUE TITLE
CC: cert_lab not extracted properly

### ISSUE THREAD

**Issue by adamjanovsky** [crocs-muni/sec-certs#82]
- When computing heuristics, `cert_lab` is not extracted properly and attempt for extraction crashes the program.
- Also, cc_cli does not process maintenance updates even when actions is specified
- We should not attempt to run further actions on files for which some of the actions failed.

**Comment by adamjanovsky** [comment]
Ok, so the problem emerged during tests as well. It seems that we attempt to retreive the `cert_lab` attribute from `None` when download or pdf processing fails. 

```
2021-05-18 12:21:53,183 - sec_certs.dataset.dataset - INFO - Deriving information about laboratories involved in certification.
Traceback (most recent call last):
  File "/Users/adam/.pyenv/versions/3.8.1/bin/cc-certs", line 11, in <module>
    load_entry_point('sec-certs', 'console_scripts', 'cc-certs')()
  File "/Users/adam/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/adam/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/adam/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/adam/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/adam/phd/projects/certificates/sec-certs/cc_cli.py", line 93, in main
    dset.compute_heuristics()
  File "/Users/adam/phd/projects/certificates/sec-certs/sec_certs/dataset/common_criteria.py", line 683, in compute_heuristics
    
  File "/Users/adam/phd/projects/certificates/sec-certs/sec_certs/dataset/common_criteria.py", line 673, in compute_cert_labs
    compute_candidate_versions()
  File "/Users/adam/phd/projects/certificates/sec-certs/sec_certs/certificate/common_criteria.py", line 586, in compute_heuristics_cert_lab
  File "/Users/adam/phd/projects/certificates/sec-certs/sec_certs/certificate/common_criteria.py", line 135, in cert_lab
    return self.anssi_cert_id
  File "/Users/adam/phd/projects/certificates/sec-certs/sec_certs/certificate/common_criteria.py", line 126, in bsi_data
    
TypeError: 'NoneType' object is not subscriptable
```
